---
- name: Arch install - Full disk encryption
  hosts: vm

  pre_tasks:

    - name: Abort if the host is not booted from the Arch install media
      fail:
        msg: "This host is not booted from the Arch install media!"
      when: ansible_nodename != 'archiso'
      tags:
        - quick_exit

    - name: Synchronize clock via NTP
      command: timedatectl set-ntp true
      tags:
        - sync_clock

  roles:
    - role: encrypted-arch
