---
- name: Set hostname
  copy:
    content: '{{ new_hostname }}'
    dest: /mnt/etc/hostname

- name: Create hosts file
  template:
    src: hosts.j2
    dest: /mnt/etc/host

- name: Enable networkmanager
  command: arch-chroot /mnt systemctl enable NetworkManager
  tags:
    - networkmanager
