---
- name: Wipe install drive and all its partitions
  command: find /dev -wholename "{{ install_drive }}*" -exec wipefs --force --all {} \;
  tags:
    - wipefs

- name: Create EFI partition
  parted:
    device: '{{ install_drive }}'
    label: gpt
    number: 1
    part_end: 512MB
    name: EFI
    flags: [esp]
    state: present

- name: Create root partition
  parted:
    device: '{{ install_drive }}'
    label: gpt
    number: 2
    part_start: 512MB
    name: root
    state: present

- name: Create and open LUKS volume
  luks_device:
    device: '{{ root_partition }}'
    keyfile: /root/keyfile
    name: root
    state: opened
