---
- name: Add loader Configuration for systemd init
  copy:
    content: >-
      {{ extra_kernel_parameters }} rd.luks.name={{ root_luks_uuid.stdout }}=root
      rd.luks.options=timeout=90s,cipher=aes-xts-plain64:sha256,size=512 root=/dev/mapper/root"
    dest: /mnt/root/kernel-command-line.txt

- name: Create Unified Kernel Image
  command: >-
    arch-chroot /mnt objcopy
      --add-section .osrel="/usr/lib/os-release"                         --change-section-vma .osrel=0x20000
      --add-section .cmdline="/root/kernel-command-line.txt"             --change-section-vma .cmdline=0x30000
      --add-section .splash="/usr/share/systemd/bootctl/splash-arch.bmp" --change-section-vma .splash=0x40000
      --add-section .linux="/boot/vmlinuz-linux"                         --change-section-vma .linux=0x2000000
      --add-section .initrd="/boot/initramfs-linux.img"                  --change-section-vma .initrd=0x3000000
      "/usr/lib/systemd/boot/efi/linuxx64.efi.stub" "/efi/EFI/Linux/linux.efi"

- name: Create boot entry for the newly created kernel
  copy:
    content: |
      title   Arch Linux
      efi     /EFI/Linux/linux.efi
    dest: /mnt/efi/loader/entries/ArchLinux.conf

# https://github.com/andreyv/sbupdate
# https://wiki.archlinux.org/index.php/Unified_Extensible_Firmware_Interface/Secure_Boot#Fully_automated_unified_kernel_generation_and_signing_with_sbupdate
